### PR TITLE
Ecto 3.0 support [updated]

### LINKED ISSUE #48: Ecto 3.0 support
I've started some initial work on this here: https://github.com/mtarnovan/kerosene/tree/ecto-3.0. I think the migration to 3 won't necessitate a lot of changes, mostly things related to pattern matching on the Query struct, which is more structured in Ecto 3. (for example `from` changed from a tuple to a `%Ecto.Query.FromExpr`, etc)

### PR DESCRIPTION
**Pull request by nathany**
Amends #47 with EctoSQL and an additional fix from @mtarnovan.

Fixes #48

### CODE REVIEW

**Comment by allyraza** [comment]
thank you everyone another gentleman open a PR request recently, please can we reconcile the changes some how so we can merge this.

**Comment by theangryangel** [comment]
From a brief inspection I believe they're effectively the same. Except the other PR has had the formatter run against the project as well, thus generated a larger patch.

**Comment by nathany** [comment]
Yes, I intentionally disabled my auto-format on save so that it would be easier to review the changes in this patch.

**Comment by allyraza** [comment]
@danturn going to merge it and release it now

**Pull request merged**
