### PR TITLE
Simple pagination mode

### PR DESCRIPTION
**Pull request by Mehonoshin**
In my application I would like to display only prev/next pagination links.
For this purpose introducing pagination mode option.

@allyraza any thoughts about such approach?

Adding tests TBD.

### CODE REVIEW

**Comment by allyraza** [comment]
Hi,

We could certainly add this to kerosene, although you can hide the links with css/js but its good to have it as part of kerosene, please can you squash the commits and make one PR instead of two if possible.

Thank you!

**Comment by Mehonoshin** [comment]
@allyraza sure, I'll add some tests and squash commits

**Comment by Mehonoshin** [comment]
@allyraza all is done! check it out

**Comment by Mehonoshin** [comment]
@allyraza ping

**Comment by allyraza** [comment]
@Mehonoshin sorry I did not get a time to make release I would like to merge and make a new release together so we have this published on hex maybe later today I will make release. Thank you!

**Pull request merged**
